Repository Gerencia-de-configuracao-e-mudancas/projeto-final-manuclarafinalv2, pull requests merged in 2025-03, with the labels that each got.

#11 feat: Sonoro
  AJR OOOHH wAAAA YAYA.m4a
  Jack-GO!.mp3
  bangbangbang.mp3
  herewegoo.mp3
  index.html
  script.js
Labels: enhancement

#3 feat: html basico
  AJR OOOHH wAAAA YAYA.m4a
  Jack-GO!.mp3
  MailartRubberstamp-Regular.otf
  NimbusSanL-Bol.otf
  bangbangbang.mp3
  collect-points-190037.mp3
  herewegoo.mp3
  index.html
  script.js
  style.css
Labels: enhancement

#16 Merge STYLES-2 into main
  audio/AJROOOHHwAAAAYAYA.m4a
  audio/Jack-GO!.mp3
  audio/bangbangbang.mp3
  audio/collect-points-190037.mp3
  audio/herewegoo.mp3
  fonts/MailartRubberstamp-Regular.otf
  fonts/NimbusSanL-Bol.otf
  fonts/NimbusSanL-Regu.ttf
  fonts/exljbris-MuseoSlab-500.otf
  icons/instagram.png
  icons/twitter.png
  icons/youtube.png
  images/Worlds_Smallest_Violin.jpeg
  images/bang.jpg
  images/weak.jpg
  index.html
  music/bang.m4a
  music/weak.m4a
  music/worldsmallestviolin.mp4
  script.js
  style.css
Labels: enhancement

#19 (fix): mobile layout
  style.css
Labels: bug

#20 Update README.md
  README.md
Labels: documentation
